version: '3'

services:
  web:
    build: .
    restart: always
    expose:
      - "8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static

    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
